### ISSUE TITLE
Add option for active screen only

### ISSUE THREAD

**Issue by IceDBorn** [DreamMaoMao/hycov#21]
Hycov right now toggles overview for all screens.

**Comment by DreamMaoMao** [comment]
done, you can try it in dev branch.
git clone -b dev https://github.com/DreamMaoMao/hycov.git

But you can't keep the current monitor in overview mode and then keep other screens in their previous layout to handle window events.  

You can only exit the overview mode of the current monitor before allowing other screens to use their previous layout methods to handle window events.

Because hyprland, unlike dwm, can't bind the layout to each monitor, it can only set the global layout
