### ISSUE TITLE
窗口位置发生变化

### ISSUE THREAD

**Issue by roukaixin** [DreamMaoMao/hycov#8]
切换 overview，点击主窗口，位置和切换之前发生了改变

**Comment by DreamMaoMao** [comment]
done [f3ebe13](https://github.com/DreamMaoMao/hycov/commit/f3ebe13b5632890abb0aa17695dd430ff1d50b02)

**Comment by DreamMaoMao** [comment]
master {
  new_is_master = true
}

It is suggested to change new_is_master to true so that the position will not change before and after the switch. Since the master layout built-in in hyprland does not expose its layout node data to the plug-in system, I cannot obtain the location of the master layout node before the switch to achieve position restoration.

**Comment by roukaixin** [comment]
那就没办法了

**Comment by DreamMaoMao** [comment]
has support #32
